"""The style gate. These also run in CI against every published post."""

from __future__ import annotations

import pytest

from aibh_pipeline.services.humanizer import scan
from aibh_pipeline.services.site import existing_posts

# A body that deliberately satisfies every structural rule, so each test can
# introduce exactly one violation and attribute the failure to it.
CLEAN_BODY = """\
## TL;DR

Cursor's new agent mode is worth 20 minutes of your evening. It won't replace
reading the diff. What it does is take the boring 80% of a refactor off your
hands, and that's a real saving.

Here's the part that matters for a solo builder. The old workflow meant
approving each edit by hand, one file at a time, which got tedious fast on
anything touching more than 3 files. You'd end up skimming. The new mode
batches the whole change into a single review, and you either take it or you
don't.

I'm not convinced by the pricing. At $20 a month it's fine if you code most
days. If you open the editor twice a week, it isn't.

The catch: the agent still can't run your test suite on its own, so nothing
here removes the need to verify. Treat it as a fast first draft.

Worth trying. Not worth switching editors for.
"""


def test_clean_body_passes(rules):
    assert scan(CLEAN_BODY, rules) == []


@pytest.mark.parametrize(
    ("snippet", "rule_fragment"),
    [
        ("This tool is a game-changer for builders.", "game-changer"),
        ("Moreover, the pricing is fair.", "moreover"),
        ("We can leverage the new API here.", "leverage-as-verb"),
        ("It's not just an editor, it's a workflow.", "not-just-x"),
        ("Whether you're a founder or a freelancer, this helps.", "whether-youre"),
        ("The tool shipped this week to all users.", "dated-language"),
        ("It launched in March 2026 for everyone.", "month-name"),
        ("Studies show that builders prefer it.", "unsourced-research"),
        ("Many developers switched over.", "vague-quantifier"),
        ("The pricing went up - a lot — for solo users.", "em-dash"),
        ("It costs 20 dollars. 🚀 Worth it.", "emoji"),
        ("## Conclusion\n\nThat's the story.", "conclusion-heading"),
        ("## Introduction\n\nHere we go.", "introduction-heading"),
        ("## What This Actually Means For Solo Builders", "title-case"),
        ("Let's dive in to the details.", "dive"),
        ("In today's fast-paced world, tools matter.", "fast-paced"),
    ],
)
def test_each_banned_pattern_is_caught(rules, snippet, rule_fragment):
    violations = scan(CLEAN_BODY + "\n\n" + snippet, rules)
    assert any(rule_fragment in v.rule for v in violations), (
        f"{rule_fragment!r} not flagged; got {[v.rule for v in violations]}"
    )


def test_structural_rules_catch_machine_rhythm(rules):
    uniform = "\n\n".join(
        ["The tool works well and the pricing is fair for most solo builders here."] * 6
    )
    rule_ids = {v.rule for v in scan(uniform, rules)}
    assert "uniform-paragraphs" in rule_ids
    assert "too-formal" in rule_ids
    assert "too-vague" in rule_ids


def test_bullet_heavy_post_is_flagged(rules):
    body = "Short intro paragraph about the thing.\n\n" + "\n".join(
        f"- point number {i}" for i in range(10)
    )
    assert "too-many-bullets" in {v.rule for v in scan(body, rules)}


def test_no_published_post_contains_banned_patterns(rules, settings):
    """Acceptance criterion: nothing generated by the pipeline may regress.

    Only posts tagged "news" are checked - the hand-written reviews predate
    these rules and are not rewritten by the pipeline.
    """
    offenders: dict[str, list[str]] = {}
    for post in existing_posts(settings.content_dir):
        if "news" not in post.tags:
            continue
        violations = scan(post.body, rules)
        if violations:
            offenders[post.slug] = sorted({v.rule for v in violations})
    assert not offenders, f"banned patterns in generated posts: {offenders}"
