"""The style gate. These also run in CI against every published post."""

from __future__ import annotations

import pytest

from aibh_pipeline.services.humanizer import scan
from aibh_pipeline.services.site import existing_posts

# A body that deliberately satisfies every structural rule, so each test can
# introduce exactly one violation and attribute the failure to it.
CLEAN_BODY = """\
## TL;DR

Cursor's new agent mode is worth 20 minutes of your evening. It won't replace
reading the diff. What it does is take the boring 80% of a refactor off your
hands, and that's a real saving.

Here's the part that matters for a solo builder. The old workflow meant
approving each edit by hand, one file at a time, which got tedious fast on
anything touching more than 3 files. You'd end up skimming. The new mode
batches the whole change into a single review, and you either take it or you
don't.

I'm not convinced by the pricing. At $20 a month it's fine if you code most
days. If you open the editor 2 days a week, it isn't, and the 14-day trial
won't tell you which of those you are.

The catch: the agent still can't run your test suite on its own, so nothing
here removes the need to verify. Treat it as a fast first draft.

Worth trying. Not worth switching editors for.
"""


def test_clean_body_passes(rules):
    assert scan(CLEAN_BODY, rules) == []


@pytest.mark.parametrize(
    ("snippet", "rule_fragment"),
    [
        ("This tool is a game-changer for builders.", "game-changer"),
        ("Moreover, the pricing is fair.", "moreover"),
        ("We can leverage the new API here.", "leverage-as-verb"),
        ("It's not just an editor, it's a workflow.", "not-just-x"),
        ("Whether you're a founder or a freelancer, this helps.", "whether-youre"),
        ("The tool shipped this week to all users.", "dated-language"),
        ("It launched in March 2026 for everyone.", "month-name"),
        ("Studies show that builders prefer it.", "unsourced-research"),
        ("Many developers switched over.", "vague-quantifier"),
        ("The pricing went up - a lot — for solo users.", "em-dash"),
        ("It costs 20 dollars. 🚀 Worth it.", "emoji"),
        ("## Conclusion\n\nThat's the story.", "conclusion-heading"),
        ("## Introduction\n\nHere we go.", "introduction-heading"),
        ("## What This Actually Means For Solo Builders", "title-case"),
        ("Let's dive in to the details.", "dive"),
        ("In today's fast-paced world, tools matter.", "fast-paced"),
    ],
)
def test_each_banned_pattern_is_caught(rules, snippet, rule_fragment):
    violations = scan(CLEAN_BODY + "\n\n" + snippet, rules)
    assert any(rule_fragment in v.rule for v in violations), (
        f"{rule_fragment!r} not flagged; got {[v.rule for v in violations]}"
    )


def test_structural_rules_catch_machine_rhythm(rules):
    uniform = "\n\n".join(
        ["The tool works well and the pricing is fair for most solo builders here."] * 6
    )
    rule_ids = {v.rule for v in scan(uniform, rules)}
    assert "uniform-paragraphs" in rule_ids
    assert "too-formal" in rule_ids
    assert "too-vague" in rule_ids


def test_bullet_heavy_post_is_flagged(rules):
    body = "Short intro paragraph about the thing.\n\n" + "\n".join(
        f"- point number {i}" for i in range(10)
    )
    assert "too-many-bullets" in {v.rule for v in scan(body, rules)}


def test_no_published_post_contains_banned_patterns(rules, settings):
    """Acceptance criterion: nothing generated by the pipeline may regress.

    Only posts tagged "news" are checked - the hand-written reviews predate
    these rules and are not rewritten by the pipeline.
    """
    offenders: dict[str, list[str]] = {}
    for post in existing_posts(settings.content_dir):
        if "news" not in post.tags:
            continue
        from aibh_pipeline.services.humanizer import ADVISORY_RULES, scan_metadata

        violations = scan(post.body, rules) + scan_metadata(
            post.title, post.description, rules
        )
        # Advisory rules are reported by the pipeline and deliberately do not
        # stop a publication, so the gate must not fail on them either -
        # otherwise a post the pipeline accepted still cannot reach the site.
        blocking = [v for v in violations if v.rule not in ADVISORY_RULES]
        if blocking:
            offenders[post.slug] = sorted({v.rule for v in blocking})
    assert not offenders, f"banned patterns in generated posts: {offenders}"


def test_the_rhythm_rules_are_calibrated_to_human_writing(rules, settings):
    """Every hand-written post on the site must clear the structural rules.

    These thresholds were measured against those posts, not guessed. If this
    fails, a limit drifted past what a person actually writes and the
    humaniser will start chasing an impossible target.
    """
    from aibh_pipeline.services.humanizer import ADVISORY_RULES, _structure_violations

    limits = rules.get("structure") or {}
    offenders = {}
    for post in existing_posts(settings.content_dir):
        # Step-by-step guides and tutorials legitimately live on lists and
        # run past the bullet limit. The pipeline writes news analysis, so
        # reviews and comparisons are the right reference shape.
        if {"guide", "tutorial"} & set(post.tags):
            continue
        violations = [
            v for v in _structure_violations(post.body, limits) if v.rule not in ADVISORY_RULES
        ]
        if violations:
            offenders[post.slug] = [f"{v.rule}: {v.excerpt}" for v in violations]
    assert not offenders, f"human-written posts fail the rhythm rules: {offenders}"


# --- advisory vs blocking -------------------------------------------------
# The "too-vague" rule wants three concrete figures, but the only legal source
# of a figure is the article's sources, and the humanizer is forbidden from
# adding statistics because it runs after the fact-checker. A draft whose
# numbers were all stripped in review therefore has no way back above the
# threshold. Runs on 12 August and 1 September died there with zero blocking
# issues everywhere else.


async def test_a_vague_post_is_published_with_a_note_not_blocked(settings, rules):
    from aibh_pipeline.services import humanizer

    clean_but_vague = (
        "## What changed\n\n"
        "OpenAI shipped a reference for its work tool. It's small.\n\n"
        "You skim it once and forget it, and that would be the reasonable "
        "response for almost everyone reading this, because the thing it "
        "documents is not the thing that will change your week. But it "
        "isn't nothing either.\n\n"
        "Don't rush. If you aren't already living in the desktop app, this "
        "won't move you, and you'll want to wait until the agent story "
        "settles into something you can plan around. Wait.\n"
    )

    class NoOpClient:
        async def complete(self, **kwargs) -> str:
            return clean_but_vague

    body, blocking = await humanizer.humanize(
        clean_but_vague, client=NoOpClient(), settings=settings, voice="voice"
    )

    assert [v.rule for v in humanizer.scan(body, rules) if v.rule == "too-vague"] == ["too-vague"]
    assert blocking == [], "an unsatisfiable style preference must not skip the day"


async def test_a_banned_word_still_blocks(settings):
    from aibh_pipeline.services import humanizer

    with_banned = (
        "## What changed\n\n"
        "This is a game-changer that will revolutionize how you work. "
        "It's seamless and robust.\n"
    )

    class StubbornClient:
        async def complete(self, **kwargs) -> str:
            return with_banned

    _, blocking = await humanizer.humanize(
        with_banned, client=StubbornClient(), settings=settings, voice="voice"
    )
    assert blocking, "hard style rules must still stop publication"
